const express = require('express');
const multer = require('multer');
const fetch = require('node-fetch');
const pdfParse = require('pdf-parse');
const fs = require('fs');
const path = require('path');
const gdsPromptV1 = require('./gds-prompt-v1');
const { buildPrototypeFiles: buildPrototypeFilesV1 } = require('./generator-v1');
const contentReviewPrompt = require('./content-review-prompt');
const gdsPromptV2 = require('./gds-prompt-v2');
const { buildPrototypeFiles: buildPrototypeFilesV2 } = require('./generator-v2');

const app = express();
const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 10 * 1024 * 1024 } });

app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(express.static(path.join(__dirname, 'public')));

// ─── GitHub helpers ───────────────────────────────────────────────────────────

async function createGitHubRepo(repoName, token) {
  const res = await fetch('https://api.github.com/user/repos', {
    method: 'POST',
    headers: {
      'Authorization': `token ${token}`,
      'Accept': 'application/vnd.github.v3+json',
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      name: repoName,
      private: false,
      auto_init: false,
      description: 'GOV.UK prototype generated by Prototype Engine'
    })
  });
  if (!res.ok) {
    const err = await res.json();
    throw new Error(`GitHub repo creation failed: ${err.message}`);
  }
  return await res.json();
}

async function pushFileToGitHub(owner, repo, filePath, content, token) {
  const res = await fetch(`https://api.github.com/repos/${owner}/${repo}/contents/${filePath}`, {
    method: 'PUT',
    headers: {
      'Authorization': `token ${token}`,
      'Accept': 'application/vnd.github.v3+json',
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      message: `Add ${filePath}`,
      content: Buffer.from(content).toString('base64')
    })
  });
  if (!res.ok) {
    const err = await res.json();
    throw new Error(`Failed to push ${filePath}: ${err.message}`);
  }
  return await res.json();
}

async function pushAllFiles(owner, repoName, files, token) {
  for (const [filePath, content] of Object.entries(files)) {
    await pushFileToGitHub(owner, repoName, filePath, content, token);
    await new Promise(r => setTimeout(r, 200));
  }
}

// ─── Render helpers ───────────────────────────────────────────────────────────

async function createRenderService(repoUrl, serviceName, renderApiKey, ownerId) {
  const res = await fetch('https://api.render.com/v1/services', {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${renderApiKey}`,
      'Content-Type': 'application/json',
      'Accept': 'application/json'
    },
    body: JSON.stringify({
      type: 'web_service',
      name: serviceName,
      ownerId: ownerId,
      repo: repoUrl,
      branch: 'main',
      autoDeploy: 'yes',
      serviceDetails: {
        env: 'node',
        buildCommand: 'npm install',
        startCommand: 'npm start',
        plan: 'free',
        region: 'oregon',
        envSpecificDetails: {
          buildCommand: 'npm install',
          startCommand: 'npm start'
        }
      }
    })
  });
  if (!res.ok) {
    const err = await res.json();
    throw new Error(`Render service creation failed: ${JSON.stringify(err)}`);
  }
  return await res.json();
}

async function pollUntilLive(protoUrl, maxWaitMs = 300000) {
  const start = Date.now();
  while (Date.now() - start < maxWaitMs) {
    await new Promise(r => setTimeout(r, 15000));
    try {
      const res = await fetch(protoUrl, { timeout: 10000 });
      if (res.ok || res.status === 302 || res.status === 301) return true;
    } catch (e) {
      // still deploying
    }
  }
  throw new Error('Prototype took too long to deploy. Try opening the link in a minute.');
}

// ─── Prototype log helpers ────────────────────────────────────────────────────

const LOG_REPO = 'proto-engine-0x';
const LOG_FILE = 'prototypes-log.json';

// v3 demo cutoff — prototypes created before this date appear on page 2+
const V3_DEMO_CUTOFF = '2025-03-25T00:00:00.000Z';

async function appendToLog(entry, owner, token) {
  let existingLog = [];
  let sha = null;
  try {
    const res = await fetch(`https://api.github.com/repos/${owner}/${LOG_REPO}/contents/${LOG_FILE}`, {
      headers: { 'Authorization': `token ${token}`, 'Accept': 'application/vnd.github.v3+json' }
    });
    if (res.ok) {
      const data = await res.json();
      sha = data.sha;
      existingLog = JSON.parse(Buffer.from(data.content, 'base64').toString('utf8'));
    }
  } catch (e) {}

  existingLog.unshift(entry);
  if (existingLog.length > 200) existingLog = existingLog.slice(0, 200);

  const body = {
    message: `Log prototype: ${entry.serviceName}`,
    content: Buffer.from(JSON.stringify(existingLog, null, 2)).toString('base64')
  };
  if (sha) body.sha = sha;

  await fetch(`https://api.github.com/repos/${owner}/${LOG_REPO}/contents/${LOG_FILE}`, {
    method: 'PUT',
    headers: {
      'Authorization': `token ${token}`,
      'Accept': 'application/vnd.github.v3+json',
      'Content-Type': 'application/json'
    },
    body: JSON.stringify(body)
  });
}

async function getLog(owner, token) {
  try {
    const res = await fetch(`https://api.github.com/repos/${owner}/${LOG_REPO}/contents/${LOG_FILE}`, {
      headers: { 'Authorization': `token ${token}`, 'Accept': 'application/vnd.github.v3+json' }
    });
    if (!res.ok) return [];
    const data = await res.json();
    return JSON.parse(Buffer.from(data.content, 'base64').toString('utf8'));
  } catch (e) {
    return [];
  }
}

// ─── v3 Landing page (demo) ───────────────────────────────────────────────────

app.get('/', (req, res) => {
  res.send(`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Prototype Engine</title>
  <style>
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: "GDS Transport", arial, sans-serif; background: #f3f2f1; min-height: 100vh; display: flex; flex-direction: column; }
    main { max-width: 960px; margin: 0 auto; padding: 40px 30px; flex: 1; width: 100%; }
    h1 { font-size: 48px; font-weight: 700; color: #0b0c0c; line-height: 1.1; margin-bottom: 8px; }
    .strapline { font-size: 24px; color: #6f777b; margin-bottom: 6px; line-height: 1.4; }
    .hero-img { display: block; max-width: 420px; width: 100%; height: auto; margin-bottom: 12px; margin-left: -68px; }
    .intro { font-size: 19px; color: #0b0c0c; line-height: 1.6; margin-bottom: 12px; }
    .feature-list { font-size: 19px; color: #0b0c0c; line-height: 1.8; padding-left: 20px; margin-bottom: 32px; }
    .feature-list li { margin-bottom: 4px; }
    .start-btn { display: inline-block; background: #00703c; color: white; padding: 12px 22px; font-size: 19px; font-weight: 700; font-family: inherit; text-decoration: none; border: none; cursor: pointer; }
    .start-btn:hover { background: #005a30; }
    .start-btn:focus { outline: 3px solid #ffdd00; outline-offset: 0; }
    footer { background: #ffffff; padding: 20px 30px; color: #0b0c0c; border-top: 1px solid #b1b4b6; font-size: 14px; text-align: center; }
    @media (max-width: 768px) { h1 { font-size: 32px; } .strapline { font-size: 20px; } .hero-img { max-width: 100%; } }
  </style>
</head>
<body>
<header style="background:#e0531a;padding:12px 0;border-bottom:none;">
  <div style="max-width:960px;margin:0 auto;padding:0 30px;">
    <a href="/" style="text-decoration:none;display:inline-flex;align-items:center;gap:10px;">
      <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
        <rect x="0" y="0" width="11" height="11" fill="white"/>
        <rect x="13" y="0" width="11" height="11" fill="white" fill-opacity="0.5"/>
        <rect x="0" y="13" width="11" height="11" fill="white" fill-opacity="0.5"/>
        <rect x="13" y="13" width="11" height="11" fill="white"/>
      </svg>
      <span style="color:white;font-size:15px;font-weight:700;font-family:arial,sans-serif;letter-spacing:-0.3px;">Prototype Engine</span>
    </a>
  </div>
</header>
<main>
  <h1>Prototype Engine</h1>
  <p class="strapline">Create a proof of concept prototype in 5 minutes</p>

  <img src="/proto_1.png" alt="A GOV.UK prototype shown on desktop and mobile" class="hero-img">

  <p class="intro">It can:</p>
  <ul class="feature-list">
    <li>Generate a working prototype from a plain English brief</li>
    <li>Handle multiple user journeys</li>
    <li>Create a shareable link for your colleagues</li>
  </ul>

  <a href="/v3" class="start-btn">Get started</a>
</main>
<footer>Built on GOV.UK Prototype Kit v13 &middot; Powered by Claude</footer>
</body>
</html>`);
});

// ─── Old launcher (hidden, accessible at /launcher) ──────────────────────────

app.get('/launcher', (req, res) => {
  res.send(`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Prototype Engine – Launcher</title>
  <style>
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: "GDS Transport", arial, sans-serif; background: #f3f2f1; min-height: 100vh; display: flex; flex-direction: column; }
    main { max-width: 960px; margin: 0 auto; padding: 40px 30px; flex: 1; width: 100%; }
    h1 { font-size: 48px; font-weight: 700; color: #0b0c0c; line-height: 1.1; margin-bottom: 10px; }
    .lede { font-size: 20px; color: #0b0c0c; margin-bottom: 40px; line-height: 1.5; }
    .version-list { list-style: none; padding: 0; display: flex; flex-direction: column; gap: 1px; background: #d8dde0; border: 1px solid #d8dde0; }
    .version-card { background: white; padding: 24px; display: flex; align-items: center; justify-content: space-between; gap: 20px; }
    .version-card:hover { background: #f8f8f8; }
    .version-info { flex: 1; }
    .version-name { font-size: 24px; font-weight: 700; color: #0b0c0c; text-decoration: none; }
    .version-name:hover { text-decoration: underline; }
    .version-desc { font-size: 16px; color: #505a5f; margin-top: 4px; }
    .badge { display: inline-block; font-size: 14px; font-weight: 700; padding: 4px 10px; text-transform: uppercase; letter-spacing: 0.5px; white-space: nowrap; }
    .badge--stable { background: #00703c; color: white; }
    .badge--beta { background: #1d70b8; color: white; }
    footer { background: #ffffff; padding: 20px 30px; color: #0b0c0c; border-top: 1px solid #b1b4b6; font-size: 14px; text-align: center; }
    @media (max-width: 768px) { h1 { font-size: 32px; } }
  </style>
</head>
<body>
<header style="background:#e0531a;padding:12px 0;border-bottom:none;">
  <div style="max-width:960px;margin:0 auto;padding:0 30px;">
    <a href="/launcher" style="text-decoration:none;display:inline-flex;align-items:center;gap:10px;">
      <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
        <rect x="0" y="0" width="11" height="11" fill="white"/>
        <rect x="13" y="0" width="11" height="11" fill="white" fill-opacity="0.5"/>
        <rect x="0" y="13" width="11" height="11" fill="white" fill-opacity="0.5"/>
        <rect x="13" y="13" width="11" height="11" fill="white"/>
      </svg>
      <span style="color:white;font-size:15px;font-weight:700;font-family:arial,sans-serif;letter-spacing:-0.3px;">Prototype Engine</span>
    </a>
  </div>
</header>
<main>
  <h1>Prototype Engine</h1>
  <p class="lede">Choose a generator version to build your GOV.UK prototype.</p>
  <ul class="version-list">
    <li class="version-card">
      <div class="version-info">
        <a href="/v1" class="version-name">v1: Simple prototypes</a>
        <p class="version-desc">Linear question flows with validation, check-your-answers and confirmation pages.</p>
      </div>
      <span class="badge badge--stable">Stable</span>
    </li>
    <li class="version-card">
      <div class="version-info">
        <a href="/v2" class="version-name">v2: Branching prototypes</a>
        <p class="version-desc">Multi-path journeys with conditional routing and branching logic.</p>
      </div>
      <span class="badge badge--beta">Beta</span>
    </li>
  </ul>
</main>
<footer>Built on GOV.UK Prototype Kit v13 &middot; Powered by Claude</footer>
</body>
</html>`);
});

// ─── v1 Frontend ──────────────────────────────────────────────────────────────

app.get('/v1', (req, res) => {
  res.send(`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Transform Prototype Engine</title>
  <style>
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: "GDS Transport", arial, sans-serif; background: #f3f2f1; min-height: 100vh; display: flex; flex-direction: column; }
    main { max-width: 960px; margin: 0 auto; padding: 40px 30px; flex: 1; width: 100%; }

    h1 { font-size: 48px; font-weight: 700; color: #0b0c0c; line-height: 1.1; margin-bottom: 20px; }
    .lede { font-size: 20px; color: #0b0c0c; margin-bottom: 40px; line-height: 1.5; }
    label { display: block; font-size: 19px; font-weight: 700; color: #0b0c0c; margin-bottom: 8px; }
    .hint { font-size: 16px; color: #505a5f; margin-bottom: 10px; }
    textarea, input[type="text"], input[type="url"] { width: 100%; padding: 10px; font-size: 19px; font-family: inherit; border: 2px solid #0b0c0c; border-radius: 0; background: white; color: #0b0c0c; margin-bottom: 24px; }
    textarea:focus, input:focus { outline: 3px solid #ffdd00; outline-offset: 0; box-shadow: inset 0 0 0 2px #0b0c0c; }
    textarea { resize: vertical; }
    .file-upload-label { display: inline-block; padding: 8px 14px; background: #f3f2f1; border: 2px solid #0b0c0c; cursor: pointer; font-size: 16px; margin-bottom: 8px; }
    .file-name { font-size: 16px; color: #505a5f; margin-bottom: 24px; }
    input[type="file"] { display: none; }
    .generate-btn { background: #00703c; color: white; border: none; padding: 13px 22px; font-size: 19px; font-weight: 700; font-family: inherit; cursor: pointer; display: flex; align-items: center; gap: 10px; }
    .generate-btn:hover { background: #005a30; }
    .generate-btn:focus { outline: 3px solid #ffdd00; outline-offset: 0; }
    .generate-btn:disabled { background: #00703c; opacity: 0.75; cursor: wait; }
    .btn-arrow { width: 20px; height: 20px; fill: white; }

    /* Progress bar */
    .progress-panel { display: none; margin-top: 24px; background: white; border: 1px solid #d8dde0; border-radius: 6px; padding: 24px; }
    .progress-panel.visible { display: block; animation: fadeIn 0.2s ease; }
    .progress-bar-track { background: #f3f2f1; height: 4px; margin-bottom: 24px; border-radius: 2px; overflow: hidden; }
    .progress-bar-fill { height: 4px; background: #1d70b8; width: 0%; transition: width 0.6s ease; border-radius: 2px; }
    .progress-bar-fill.complete { background: #00703c; }
    .progress-steps { list-style: none; padding: 0; }
    .progress-steps li { font-size: 14px; color: #b1b4b6; padding: 9px 0; display: flex; align-items: center; gap: 12px; border-bottom: 1px solid #f3f2f1; transition: color 0.2s; }
    .progress-steps li:last-child { border-bottom: none; }
    .progress-steps li.active { color: #0b0c0c; font-weight: 600; }
    .progress-steps li.done { color: #00703c; }
    .step-icon { width: 16px; text-align: center; font-size: 12px; flex-shrink: 0; }

    /* Done panel */
    .done-panel { display: none; margin-top: 30px; background: white; border-left: 5px solid #00703c; padding: 24px; }
    .done-panel.visible { display: block; animation: fadeIn 0.4s ease; }
    @keyframes fadeIn { from { opacity: 0; transform: translateY(8px); } to { opacity: 1; transform: translateY(0); } }
    .done-header { display: flex; align-items: center; gap: 14px; margin-bottom: 16px; }
    .done-tick-circle { width: 40px; height: 40px; border-radius: 50%; background: #00703c; display: flex; align-items: center; justify-content: center; flex-shrink: 0; animation: popIn 0.4s cubic-bezier(0.34,1.56,0.64,1) both; }
    @keyframes popIn { from { transform: scale(0); } to { transform: scale(1); } }
    .done-tick-circle svg { width: 22px; height: 22px; fill: none; stroke: white; stroke-width: 3; stroke-linecap: round; stroke-linejoin: round; }
    .done-tick-circle svg path { stroke-dasharray: 40; stroke-dashoffset: 40; animation: drawTick 0.35s ease 0.3s forwards; }
    @keyframes drawTick { to { stroke-dashoffset: 0; } }
    .done-title { font-size: 24px; font-weight: 700; color: #0b0c0c; }
    .done-sub { font-size: 16px; color: #505a5f; margin-bottom: 20px; }
    .open-proto-btn { display: inline-block; background: #1d70b8; color: white; padding: 12px 20px; font-size: 19px; font-weight: 700; font-family: inherit; text-decoration: none; }
    .open-proto-btn:hover { background: #003078; }

    /* Error panel */
    .error-panel { display: none; margin-top: 30px; background: white; border-left: 5px solid #d4351c; padding: 24px; }
    .error-panel.visible { display: block; }
    .error-title { font-size: 19px; font-weight: 700; color: #0b0c0c; margin-bottom: 8px; }
    .error-msg { font-size: 16px; color: #505a5f; }

    /* Spinner */
    .spinner { display: inline-block; width: 16px; height: 16px; border: 2px solid rgba(255,255,255,0.4); border-top-color: white; border-radius: 50%; animation: spin 0.7s linear infinite; }
    @keyframes spin { to { transform: rotate(360deg); } }


    footer { background: #ffffff; padding: 20px 30px; color: #0b0c0c; border-top: 1px solid #b1b4b6; font-size: 14px; text-align: center; }
@media (max-width: 768px) { h1 { font-size: 32px; } }
  </style>
</head>
<body>
<header style="background:#e0531a;padding:12px 0;border-bottom:none;">
  <div style="max-width:960px;margin:0 auto;padding:0 30px;">
    <a href="/" style="text-decoration:none;display:inline-flex;align-items:center;gap:10px;">
      <svg class="pe-logo" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
        <rect x="0" y="0" width="11" height="11" fill="white"/>
        <rect x="13" y="0" width="11" height="11" fill="white" fill-opacity="0.5"/>
        <rect x="0" y="13" width="11" height="11" fill="white" fill-opacity="0.5"/>
        <rect x="13" y="13" width="11" height="11" fill="white"/>
      </svg>
      <span style="color:white;font-size:15px;font-weight:700;font-family:arial,sans-serif;letter-spacing:-0.3px;">Prototype Engine</span>
    </a>
  </div>
</header>
<main>
<div style="max-width: 600px;">
    <div>
      <h1>Build a GOV.UK prototype</h1>
      <p class="lede">Describe your service and Claude will build a working GOV.UK prototype — no code required.</p>
      <form id="generateForm" enctype="multipart/form-data">
        <div>
          <label for="q1">Who are the users and what are their needs?</label>
          <textarea id="q1" name="q1" rows="3" placeholder="e.g. Parents applying for free school meals"></textarea>
        </div>
        <div>
          <label for="q2">What does the service need to achieve?</label>
          <textarea id="q2" name="q2" rows="3" placeholder="e.g. Help parents check eligibility and apply"></textarea>
        </div>
        <div>
          <label for="q3">What content principles should we apply?</label>
          <textarea id="q3" name="q3" rows="3" placeholder="e.g. Plain English, no jargon"></textarea>
        </div>
        <div>
          <label for="pdf">Upload a PDF (optional)</label>
          <p class="hint">Policy documents, existing service specs, research findings.</p>
          <label class="file-upload-label" for="pdf">Choose file</label>
          <input type="file" id="pdf" name="pdf" accept=".pdf">
          <div class="file-name" id="fileName">No file chosen</div>
        </div>
        <div>
          <label for="url">Reference URL (optional)</label>
          <p class="hint">A live service or document to reference.</p>
          <input type="url" id="url" name="url" placeholder="https://www.gov.uk/example">
        </div>
        <div style="margin-bottom: 24px;">
          <div style="display: flex; align-items: flex-start; gap: 10px;">
            <input type="checkbox" id="contentReview" name="contentReview" value="true" style="width: auto; min-width: 24px; height: 24px; margin: 0; cursor: pointer;">
            <div>
              <label for="contentReview" style="display: inline; font-size: 19px; font-weight: 700; color: #0b0c0c; margin-bottom: 0; cursor: pointer;">Apply content review</label>
              <span style="display: inline-block; margin-left: 8px; padding: 2px 8px; background: #6f3764; color: white; font-size: 12px; font-weight: 700; text-transform: uppercase; letter-spacing: 1px; line-height: 1.6;">EXPERIMENTAL</span>
              <p class="hint" style="margin-top: 6px; margin-bottom: 0;">Improves question wording, hints, and error messages using GDS content design rules.</p>
            </div>
          </div>
        </div>
        <button type="submit" class="generate-btn" id="generateBtn">
          <span id="btnText">Generate prototype</span>
          <svg class="btn-arrow" id="btnArrow" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 60 60">
            <path d="M0 20h40l-8-8 4-4 16 16-16 16-4-4 8-8H0z"/>
          </svg>
        </button>
        <p style="margin-top:12px;font-size:15px;color:#505a5f;">or <a href="/prototypes" style="color:#505a5f;">view previously generated prototypes</a></p>
      </form>

      <!-- Progress panel -->
      <div class="progress-panel" id="progressPanel">
        <div class="progress-bar-track">
          <div class="progress-bar-fill" id="progressBar"></div>
        </div>
        <ul class="progress-steps">
          <li id="step-pdf" style="display:none;"><span class="step-icon" id="icon-pdf">–</span> Reading document</li>
          <li id="step-claude"><span class="step-icon" id="icon-claude">–</span> Generating with Claude</li>
          <li id="step-github"><span class="step-icon" id="icon-github">–</span> Pushing to GitHub</li>
          <li id="step-render"><span class="step-icon" id="icon-render">–</span> Creating Render service</li>
          <li id="step-deploy"><span class="step-icon" id="icon-deploy">–</span> Waiting for prototype to go live</li>
        </ul>
      </div>

      <!-- Done panel -->
      <div class="done-panel" id="donePanel">
        <div class="done-header">
          <div class="done-tick-circle">
            <svg viewBox="0 0 24 24"><path d="M4 12l5 5L20 7"/></svg>
          </div>
          <div class="done-title">Your prototype is live</div>
        </div>
        <p class="done-sub">It is ready to use. Share the link with your team.</p>
        <a href="#" id="openProtoBtn" class="open-proto-btn" target="_blank" rel="noopener">Open prototype</a>
        <div id="pdfTruncatedNotice" style="display:none; margin-top: 20px; padding: 15px 20px; border-left: 10px solid #b1b4b6; font-size: 16px; color: #0b0c0c;">Your document was long so we summarised the most relevant parts. The prototype is based on that summary.</div>
      </div>

      <!-- Error panel -->
      <div class="error-panel" id="errorPanel">
        <div class="error-title">Something went wrong</div>
        <div class="error-msg" id="errorMsg"></div>
      </div>
    </div>

  </div>
</main>
<footer>Built on GOV.UK Prototype Kit v13 &middot; Powered by Claude</footer>

<script>
  document.getElementById('pdf').addEventListener('change', function() {
    document.getElementById('fileName').textContent = this.files[0] ? this.files[0].name : 'No file chosen';
  });

  // Step state helpers
  function setStep(stepId, iconId, state) {
    const li = document.getElementById(stepId);
    const icon = document.getElementById(iconId);
    li.className = state;
    if (state === 'active') icon.textContent = '●';
    else if (state === 'done') icon.textContent = '✓';
    else icon.textContent = '–';
  }

  // Timed fake progress that advances through steps on a schedule
  // Real done only fires when server responds
  let progressTimer = null;

  function startFakeProgress(hasPdf) {
    const bar = document.getElementById('progressBar');
    const pdfStep = document.getElementById('step-pdf');
    let steps;

    if (hasPdf) {
      pdfStep.style.display = '';
      steps = [
        { stepId: 'step-pdf',     iconId: 'icon-pdf',     delay: 0,     pct: 10 },
        { stepId: 'step-claude',  iconId: 'icon-claude',  delay: 12000, pct: 25 },
        { stepId: 'step-github',  iconId: 'icon-github',  delay: 24000, pct: 50 },
        { stepId: 'step-render',  iconId: 'icon-render',  delay: 36000, pct: 65 },
        { stepId: 'step-deploy',  iconId: 'icon-deploy',  delay: 50000, pct: 80 }
      ];
    } else {
      pdfStep.style.display = 'none';
      steps = [
        { stepId: 'step-claude',  iconId: 'icon-claude',  delay: 0,     pct: 15 },
        { stepId: 'step-github',  iconId: 'icon-github',  delay: 18000, pct: 45 },
        { stepId: 'step-render',  iconId: 'icon-render',  delay: 30000, pct: 65 },
        { stepId: 'step-deploy',  iconId: 'icon-deploy',  delay: 45000, pct: 80 }
      ];
    }

    let prevStepId = null, prevIconId = null;
    steps.forEach(function(s) {
      const t = setTimeout(function() {
        if (prevStepId) setStep(prevStepId, prevIconId, 'done');
        setStep(s.stepId, s.iconId, 'active');
        bar.style.width = s.pct + '%';
        prevStepId = s.stepId;
        prevIconId = s.iconId;
      }, s.delay);
      if (!progressTimer) progressTimer = [];
      progressTimer.push(t);
    });
  }

  function stopFakeProgress() {
    if (progressTimer) progressTimer.forEach(clearTimeout);
    progressTimer = null;
  }

  document.getElementById('generateForm').addEventListener('submit', async function(e) {
    e.preventDefault();

    const btn = document.getElementById('generateBtn');
    const btnText = document.getElementById('btnText');
    const btnArrow = document.getElementById('btnArrow');
    const progressPanel = document.getElementById('progressPanel');
    const donePanel = document.getElementById('donePanel');
    const errorPanel = document.getElementById('errorPanel');
    const bar = document.getElementById('progressBar');
    const hasPdf = document.getElementById('pdf').files.length > 0;

    // Reset UI
    donePanel.className = 'done-panel';
    errorPanel.className = 'error-panel';
    document.getElementById('pdfTruncatedNotice').style.display = 'none';
    progressPanel.className = 'progress-panel visible';
    bar.style.width = '5%';
    bar.className = 'progress-bar-fill';
    var allSteps = ['step-claude','step-github','step-render','step-deploy'];
    if (hasPdf) allSteps.unshift('step-pdf');
    allSteps.forEach(function(id) {
      document.getElementById(id).className = '';
      var iconId = 'icon-' + id.replace('step-', '');
      document.getElementById(iconId).textContent = '–';
    });

    btn.disabled = true;
    btnArrow.style.display = 'none';
    btnText.innerHTML = '<span class="spinner"></span> Generating&hellip;';

    startFakeProgress(hasPdf);

    try {
      const formData = new FormData(this);
      const response = await fetch('/generate-v1', { method: 'POST', body: formData });

      stopFakeProgress();

      if (!response.ok) {
        const err = await response.json().catch(function() { return { error: 'Unknown error' }; });
        throw new Error(err.error || 'Something went wrong');
      }

      const result = await response.json();

      // All steps done
      bar.style.width = '100%';
      bar.className = 'progress-bar-fill complete';
      var doneSteps = ['step-claude','step-github','step-render','step-deploy'];
      if (hasPdf) doneSteps.unshift('step-pdf');
      doneSteps.forEach(function(id) {
        setStep(id, 'icon-' + id.replace('step-', ''), 'done');
      });

      // Show done panel
      progressPanel.className = 'progress-panel';
      document.getElementById('openProtoBtn').href = result.url;
      donePanel.className = 'done-panel visible';

      // Show truncation notice if applicable
      if (result.pdfTruncated) {
        document.getElementById('pdfTruncatedNotice').style.display = 'block';
      }

    } catch (err) {
      stopFakeProgress();
      progressPanel.className = 'progress-panel';
      document.getElementById('errorMsg').textContent = err.message || 'Try again or simplify your brief.';
      errorPanel.className = 'error-panel visible';
    }

    btn.disabled = false;
    btnArrow.style.display = '';
    btnText.textContent = 'Generate prototype';
  });
</script>
</body>
</html>`);
});

// ─── v1 Generate endpoint ─────────────────────────────────────────────────────

app.post('/generate-v1', upload.single('pdf'), async (req, res) => {
  try {
    const { q1, q2, q3, url } = req.body;
    const brief = [q1, q2, q3].filter(Boolean).map((s, i) => {
      const labels = ['Users and needs', 'Service goals', 'Content principles'];
      return labels[i] + ': ' + s.trim();
    }).join('\n\n');
    const apiKey = process.env.ANTHROPIC_API_KEY;
    const githubToken = process.env.GITHUB_TOKEN;
    const renderApiKey = process.env.RENDER_API_KEY;
    const renderOwnerId = process.env.RENDER_OWNER_ID;
    const githubUsername = process.env.GITHUB_USERNAME;

    if (!apiKey) return res.status(500).json({ error: 'ANTHROPIC_API_KEY not set' });
    if (!githubToken) return res.status(500).json({ error: 'GITHUB_TOKEN not set' });
    if (!renderApiKey) return res.status(500).json({ error: 'RENDER_API_KEY not set' });
    if (!renderOwnerId) return res.status(500).json({ error: 'RENDER_OWNER_ID not set' });
    if (!githubUsername) return res.status(500).json({ error: 'GITHUB_USERNAME not set' });
    if (!q1 || q1.trim().length < 5) return res.status(400).json({ error: 'Tell us who the users are and what they need' });

    // Step 1: PDF summarisation
    let pdfSummary = null;
    let pdfTruncated = false;
    if (req.file) {
      try {
        const pdfData = await pdfParse(req.file.buffer);
        let pdfText = pdfData.text;
        if (pdfText.length > 15000) {
          if (pdfText.length > 80000) {
            pdfText = pdfText.slice(0, 80000);
            pdfTruncated = true;
          }
          try {
            const summaryResponse = await fetch('https://api.anthropic.com/v1/messages', {
              method: 'POST',
              headers: {
                'Content-Type': 'application/json',
                'x-api-key': apiKey,
                'anthropic-version': '2023-06-01'
              },
              body: JSON.stringify({
                model: 'claude-sonnet-4-6',
                max_tokens: 2000,
                system: 'You are a government policy analyst. You will receive a service brief and a policy document. Extract and summarise only the content relevant to the brief. Return a clean markdown summary covering: eligibility rules and criteria, evidence requirements, key process steps and timeframes, any user-facing terminology that must be used, and any exclusions or special cases. Be concise. Maximum 1500 words.',
                messages: [{ role: 'user', content: `Brief: ${brief.trim()}\n\nDocument:\n${pdfText}` }]
              })
            });
            if (summaryResponse.ok) {
              const summaryData = await summaryResponse.json();
              pdfSummary = summaryData.content[0].text.trim();
            }
          } catch (e) {
            console.error('PDF summarisation failed, continuing without summary:', e.message);
          }
        } else {
          pdfSummary = pdfText;
        }
      } catch (e) {
        console.error('PDF parsing failed:', e.message);
      }
    }

    // Step 2: Claude generation
    let userMessage = `Brief: ${brief.trim()}`;
    if (pdfSummary) {
      userMessage += `\n\nPolicy document summary — use this to inform eligibility rules, question wording, hints, confirmation content, and any guidance:\n${pdfSummary}`;
    }
    if (url && url.trim()) userMessage += `\n\nReference URL: ${url.trim()}`;
    userMessage += '\n\nReturn only the JSON object. No explanation. No markdown.';

    const claudeResponse = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': apiKey,
        'anthropic-version': '2023-06-01'
      },
      body: JSON.stringify({
        model: 'claude-sonnet-4-6',
        max_tokens: 4000,
        system: gdsPromptV1,
        messages: [{ role: 'user', content: userMessage }]
      })
    });

    if (!claudeResponse.ok) {
      const err = await claudeResponse.json();
      throw new Error(err.error?.message || 'Claude API error');
    }

    const claudeData = await claudeResponse.json();
    const rawText = claudeData.content[0].text.trim();

    let spec;
    try {
      const clean = rawText.replace(/^```json\s*/i, '').replace(/^```\s*/i, '').replace(/```\s*$/i, '').trim();
      spec = JSON.parse(clean);
    } catch (e) {
      throw new Error('Claude returned invalid JSON. Try simplifying your brief.');
    }

    if (!spec.serviceName || !spec.questions || spec.questions.length < 1) {
      throw new Error('Prototype spec incomplete. Try again.');
    }

    // Optional content review pass
    if (req.body.contentReview === 'true') {
      try {
        const reviewResponse = await fetch('https://api.anthropic.com/v1/messages', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'x-api-key': apiKey,
            'anthropic-version': '2023-06-01'
          },
          body: JSON.stringify({
            model: 'claude-sonnet-4-6',
            max_tokens: 2000,
            system: contentReviewPrompt,
            messages: [{ role: 'user', content: JSON.stringify(spec) + '\n\nReturn only the improved JSON object. No explanation. No markdown.' }]
          })
        });

        if (reviewResponse.ok) {
          const reviewData = await reviewResponse.json();
          const reviewText = reviewData.content[0].text.trim();
          const cleanReview = reviewText.replace(/^```json\s*/i, '').replace(/^```\s*/i, '').replace(/```\s*$/i, '').trim();
          spec = JSON.parse(cleanReview);
        }
      } catch (e) {
        console.error('Content review pass failed, continuing with original spec:', e.message);
      }
    }

    // Step 2: Build and push to GitHub
    const files = buildPrototypeFilesV1(spec);
    const timestamp = Date.now();
    const repoName = `prototype-${timestamp}`;

    await createGitHubRepo(repoName, githubToken);
    await pushAllFiles(githubUsername, repoName, files, githubToken);

    const repoUrl = `https://github.com/${githubUsername}/${repoName}`;

    // Step 3: Create Render service
    const serviceName = `prototype-${timestamp}`;
    const renderData = await createRenderService(repoUrl, serviceName, renderApiKey, renderOwnerId);

    const serviceId = renderData.service?.id;
    if (!serviceId) throw new Error('Render did not return a service ID');

    // Step 4: Poll until actually live
    const protoUrl = `https://${serviceName}.onrender.com`;
    await pollUntilLive(protoUrl);
    await new Promise(r => setTimeout(r, 20000));

    // Log it (fire and forget)
    appendToLog({
      serviceName: spec.serviceName,
      brief: brief.trim().slice(0, 120),
      url: protoUrl,
      repoUrl,
      createdAt: new Date().toISOString()
    }, githubUsername, githubToken).catch(e => console.error('Log write failed:', e));

    res.json({ url: protoUrl, repoUrl, pdfTruncated });

  } catch (err) {
    console.error(err);
    if (!res.headersSent) res.status(500).json({ error: err.message });
  }
});

// ─── v2 Frontend ──────────────────────────────────────────────────────────────

app.get('/v2', (req, res) => {
  res.send(`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Branching Prototypes — Prototype Engine</title>
  <style>
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: "GDS Transport", arial, sans-serif; background: #f3f2f1; min-height: 100vh; display: flex; flex-direction: column; }
    main { max-width: 960px; margin: 0 auto; padding: 40px 30px; flex: 1; width: 100%; }

    h1 { font-size: 48px; font-weight: 700; color: #0b0c0c; line-height: 1.1; margin-bottom: 20px; }
    .lede { font-size: 20px; color: #0b0c0c; margin-bottom: 40px; line-height: 1.5; }
    label { display: block; font-size: 19px; font-weight: 700; color: #0b0c0c; margin-bottom: 8px; }
    .hint { font-size: 16px; color: #505a5f; margin-bottom: 10px; }
    textarea, input[type="text"], input[type="url"] { width: 100%; padding: 10px; font-size: 19px; font-family: inherit; border: 2px solid #0b0c0c; border-radius: 0; background: white; color: #0b0c0c; margin-bottom: 24px; }
    textarea:focus, input:focus { outline: 3px solid #ffdd00; outline-offset: 0; box-shadow: inset 0 0 0 2px #0b0c0c; }
    textarea { resize: vertical; }
    .file-upload-label { display: inline-block; padding: 8px 14px; background: #f3f2f1; border: 2px solid #0b0c0c; cursor: pointer; font-size: 16px; margin-bottom: 8px; }
    .file-name { font-size: 16px; color: #505a5f; margin-bottom: 24px; }
    input[type="file"] { display: none; }
    .generate-btn { background: #00703c; color: white; border: none; padding: 13px 22px; font-size: 19px; font-weight: 700; font-family: inherit; cursor: pointer; display: flex; align-items: center; gap: 10px; }
    .generate-btn:hover { background: #005a30; }
    .generate-btn:focus { outline: 3px solid #ffdd00; outline-offset: 0; }
    .generate-btn:disabled { background: #00703c; opacity: 0.75; cursor: wait; }
    .btn-arrow { width: 20px; height: 20px; fill: white; }

    /* Progress bar */
    .progress-panel { display: none; margin-top: 24px; background: white; border: 1px solid #d8dde0; border-radius: 6px; padding: 24px; }
    .progress-panel.visible { display: block; animation: fadeIn 0.2s ease; }
    .progress-bar-track { background: #f3f2f1; height: 4px; margin-bottom: 24px; border-radius: 2px; overflow: hidden; }
    .progress-bar-fill { height: 4px; background: #1d70b8; width: 0%; transition: width 0.6s ease; border-radius: 2px; }
    .progress-bar-fill.complete { background: #00703c; }
    .progress-steps { list-style: none; padding: 0; }
    .progress-steps li { font-size: 14px; color: #b1b4b6; padding: 9px 0; display: flex; align-items: center; gap: 12px; border-bottom: 1px solid #f3f2f1; transition: color 0.2s; }
    .progress-steps li:last-child { border-bottom: none; }
    .progress-steps li.active { color: #0b0c0c; font-weight: 600; }
    .progress-steps li.done { color: #00703c; }
    .step-icon { width: 16px; text-align: center; font-size: 12px; flex-shrink: 0; }

    /* Done panel */
    .done-panel { display: none; margin-top: 30px; background: white; border-left: 5px solid #00703c; padding: 24px; }
    .done-panel.visible { display: block; animation: fadeIn 0.4s ease; }
    @keyframes fadeIn { from { opacity: 0; transform: translateY(8px); } to { opacity: 1; transform: translateY(0); } }
    .done-header { display: flex; align-items: center; gap: 14px; margin-bottom: 16px; }
    .done-tick-circle { width: 40px; height: 40px; border-radius: 50%; background: #00703c; display: flex; align-items: center; justify-content: center; flex-shrink: 0; animation: popIn 0.4s cubic-bezier(0.34,1.56,0.64,1) both; }
    @keyframes popIn { from { transform: scale(0); } to { transform: scale(1); } }
    .done-tick-circle svg { width: 22px; height: 22px; fill: none; stroke: white; stroke-width: 3; stroke-linecap: round; stroke-linejoin: round; }
    .done-tick-circle svg path { stroke-dasharray: 40; stroke-dashoffset: 40; animation: drawTick 0.35s ease 0.3s forwards; }
    @keyframes drawTick { to { stroke-dashoffset: 0; } }
    .done-title { font-size: 24px; font-weight: 700; color: #0b0c0c; }
    .done-sub { font-size: 16px; color: #505a5f; margin-bottom: 20px; }
    .open-proto-btn { display: inline-block; background: #1d70b8; color: white; padding: 12px 20px; font-size: 19px; font-weight: 700; font-family: inherit; text-decoration: none; }
    .open-proto-btn:hover { background: #003078; }

    /* Error panel */
    .error-panel { display: none; margin-top: 30px; background: white; border-left: 5px solid #d4351c; padding: 24px; }
    .error-panel.visible { display: block; }
    .error-title { font-size: 19px; font-weight: 700; color: #0b0c0c; margin-bottom: 8px; }
    .error-msg { font-size: 16px; color: #505a5f; }

    /* Spinner */
    .spinner { display: inline-block; width: 16px; height: 16px; border: 2px solid rgba(255,255,255,0.4); border-top-color: white; border-radius: 50%; animation: spin 0.7s linear infinite; }
    @keyframes spin { to { transform: rotate(360deg); } }


    footer { background: #ffffff; padding: 20px 30px; color: #0b0c0c; border-top: 1px solid #b1b4b6; font-size: 14px; text-align: center; }
@media (max-width: 768px) { h1 { font-size: 32px; } }
  </style>
</head>
<body>
<header style="background:#e0531a;padding:12px 0;border-bottom:none;">
  <div style="max-width:960px;margin:0 auto;padding:0 30px;">
    <a href="/" style="text-decoration:none;display:inline-flex;align-items:center;gap:10px;">
      <svg class="pe-logo" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
        <rect x="0" y="0" width="11" height="11" fill="white"/>
        <rect x="13" y="0" width="11" height="11" fill="white" fill-opacity="0.5"/>
        <rect x="0" y="13" width="11" height="11" fill="white" fill-opacity="0.5"/>
        <rect x="13" y="13" width="11" height="11" fill="white"/>
      </svg>
      <span style="color:white;font-size:15px;font-weight:700;font-family:arial,sans-serif;letter-spacing:-0.3px;">Prototype Engine</span>
    </a>
  </div>
</header>
<main>
<div style="max-width: 600px;">
    <div>
      <h1>Build a branching prototype</h1>
      <p class="lede">Describe your service and Claude will build a working GOV.UK prototype with conditional branching — no code required.</p>
      <form id="generateForm" enctype="multipart/form-data">
        <div>
          <label for="q1">Who are the users and what are their needs?</label>
          <textarea id="q1" name="q1" rows="3" placeholder="e.g. Parents applying for free school meals"></textarea>
        </div>
        <div>
          <label for="q2">What does the service need to achieve?</label>
          <textarea id="q2" name="q2" rows="3" placeholder="e.g. Help parents check eligibility and apply"></textarea>
        </div>
        <div>
          <label for="q3">What content principles should we apply?</label>
          <textarea id="q3" name="q3" rows="3" placeholder="e.g. Plain English, no jargon"></textarea>
        </div>
        <div>
          <label for="pdf">Upload a PDF (optional)</label>
          <p class="hint">Policy documents, existing service specs, research findings.</p>
          <label class="file-upload-label" for="pdf">Choose file</label>
          <input type="file" id="pdf" name="pdf" accept=".pdf">
          <div class="file-name" id="fileName">No file chosen</div>
        </div>
        <div>
          <label for="url">Reference URL (optional)</label>
          <p class="hint">A live service or document to reference.</p>
          <input type="url" id="url" name="url" placeholder="https://www.gov.uk/example">
        </div>
        <button type="submit" class="generate-btn" id="generateBtn">
          <span id="btnText">Generate prototype</span>
          <svg class="btn-arrow" id="btnArrow" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 60 60">
            <path d="M0 20h40l-8-8 4-4 16 16-16 16-4-4 8-8H0z"/>
          </svg>
        </button>
        <p style="margin-top:12px;font-size:15px;color:#505a5f;">or <a href="/prototypes" style="color:#505a5f;">view previously generated prototypes</a></p>
      </form>

      <!-- Progress panel -->
      <div class="progress-panel" id="progressPanel">
        <div class="progress-bar-track">
          <div class="progress-bar-fill" id="progressBar"></div>
        </div>
        <ul class="progress-steps">
          <li id="step-pdf" style="display:none;"><span class="step-icon" id="icon-pdf">–</span> Reading document</li>
          <li id="step-claude"><span class="step-icon" id="icon-claude">–</span> Generating with Claude</li>
          <li id="step-github"><span class="step-icon" id="icon-github">–</span> Pushing to GitHub</li>
          <li id="step-render"><span class="step-icon" id="icon-render">–</span> Creating Render service</li>
          <li id="step-deploy"><span class="step-icon" id="icon-deploy">–</span> Waiting for prototype to go live</li>
        </ul>
      </div>

      <!-- Done panel -->
      <div class="done-panel" id="donePanel">
        <div class="done-header">
          <div class="done-tick-circle">
            <svg viewBox="0 0 24 24"><path d="M4 12l5 5L20 7"/></svg>
          </div>
          <div class="done-title">Your prototype is live</div>
        </div>
        <p class="done-sub">It is ready to use. Share the link with your team.</p>
        <a href="#" id="openProtoBtn" class="open-proto-btn" target="_blank" rel="noopener">Open prototype</a>
        <div id="pdfTruncatedNotice" style="display:none; margin-top: 20px; padding: 15px 20px; border-left: 10px solid #b1b4b6; font-size: 16px; color: #0b0c0c;">Your document was long so we summarised the most relevant parts. The prototype is based on that summary.</div>
      </div>

      <!-- Error panel -->
      <div class="error-panel" id="errorPanel">
        <div class="error-title">Something went wrong</div>
        <div class="error-msg" id="errorMsg"></div>
      </div>
    </div>

  </div>
</main>
<footer>Built on GOV.UK Prototype Kit v13 &middot; Powered by Claude</footer>

<script>
  document.getElementById('pdf').addEventListener('change', function() {
    document.getElementById('fileName').textContent = this.files[0] ? this.files[0].name : 'No file chosen';
  });

  // Step state helpers
  function setStep(stepId, iconId, state) {
    const li = document.getElementById(stepId);
    const icon = document.getElementById(iconId);
    li.className = state;
    if (state === 'active') icon.textContent = '●';
    else if (state === 'done') icon.textContent = '✓';
    else icon.textContent = '–';
  }

  // Timed fake progress that advances through steps on a schedule
  // Real done only fires when server responds
  let progressTimer = null;

  function startFakeProgress(hasPdf) {
    const bar = document.getElementById('progressBar');
    const pdfStep = document.getElementById('step-pdf');
    let steps;

    if (hasPdf) {
      pdfStep.style.display = '';
      steps = [
        { stepId: 'step-pdf',     iconId: 'icon-pdf',     delay: 0,     pct: 10 },
        { stepId: 'step-claude',  iconId: 'icon-claude',  delay: 12000, pct: 25 },
        { stepId: 'step-github',  iconId: 'icon-github',  delay: 24000, pct: 50 },
        { stepId: 'step-render',  iconId: 'icon-render',  delay: 36000, pct: 65 },
        { stepId: 'step-deploy',  iconId: 'icon-deploy',  delay: 50000, pct: 80 }
      ];
    } else {
      pdfStep.style.display = 'none';
      steps = [
        { stepId: 'step-claude',  iconId: 'icon-claude',  delay: 0,     pct: 15 },
        { stepId: 'step-github',  iconId: 'icon-github',  delay: 18000, pct: 45 },
        { stepId: 'step-render',  iconId: 'icon-render',  delay: 30000, pct: 65 },
        { stepId: 'step-deploy',  iconId: 'icon-deploy',  delay: 45000, pct: 80 }
      ];
    }

    let prevStepId = null, prevIconId = null;
    steps.forEach(function(s) {
      const t = setTimeout(function() {
        if (prevStepId) setStep(prevStepId, prevIconId, 'done');
        setStep(s.stepId, s.iconId, 'active');
        bar.style.width = s.pct + '%';
        prevStepId = s.stepId;
        prevIconId = s.iconId;
      }, s.delay);
      if (!progressTimer) progressTimer = [];
      progressTimer.push(t);
    });
  }

  function stopFakeProgress() {
    if (progressTimer) progressTimer.forEach(clearTimeout);
    progressTimer = null;
  }

  document.getElementById('generateForm').addEventListener('submit', async function(e) {
    e.preventDefault();

    const btn = document.getElementById('generateBtn');
    const btnText = document.getElementById('btnText');
    const btnArrow = document.getElementById('btnArrow');
    const progressPanel = document.getElementById('progressPanel');
    const donePanel = document.getElementById('donePanel');
    const errorPanel = document.getElementById('errorPanel');
    const bar = document.getElementById('progressBar');
    const hasPdf = document.getElementById('pdf').files.length > 0;

    // Reset UI
    donePanel.className = 'done-panel';
    errorPanel.className = 'error-panel';
    document.getElementById('pdfTruncatedNotice').style.display = 'none';
    progressPanel.className = 'progress-panel visible';
    bar.style.width = '5%';
    bar.className = 'progress-bar-fill';
    var allSteps = ['step-claude','step-github','step-render','step-deploy'];
    if (hasPdf) allSteps.unshift('step-pdf');
    allSteps.forEach(function(id) {
      document.getElementById(id).className = '';
      var iconId = 'icon-' + id.replace('step-', '');
      document.getElementById(iconId).textContent = '–';
    });

    btn.disabled = true;
    btnArrow.style.display = 'none';
    btnText.innerHTML = '<span class="spinner"></span> Generating&hellip;';

    startFakeProgress(hasPdf);

    try {
      const formData = new FormData(this);
      const response = await fetch('/generate-v2', { method: 'POST', body: formData });

      stopFakeProgress();

      if (!response.ok) {
        const err = await response.json().catch(function() { return { error: 'Unknown error' }; });
        throw new Error(err.error || 'Something went wrong');
      }

      const result = await response.json();

      // All steps done
      bar.style.width = '100%';
      bar.className = 'progress-bar-fill complete';
      var doneSteps = ['step-claude','step-github','step-render','step-deploy'];
      if (hasPdf) doneSteps.unshift('step-pdf');
      doneSteps.forEach(function(id) {
        setStep(id, 'icon-' + id.replace('step-', ''), 'done');
      });

      // Show done panel
      progressPanel.className = 'progress-panel';
      document.getElementById('openProtoBtn').href = result.url;
      donePanel.className = 'done-panel visible';

      // Show truncation notice if applicable
      if (result.pdfTruncated) {
        document.getElementById('pdfTruncatedNotice').style.display = 'block';
      }

    } catch (err) {
      stopFakeProgress();
      progressPanel.className = 'progress-panel';
      document.getElementById('errorMsg').textContent = err.message || 'Try again or simplify your brief.';
      errorPanel.className = 'error-panel visible';
    }

    btn.disabled = false;
    btnArrow.style.display = '';
    btnText.textContent = 'Generate prototype';
  });
</script>
</body>
</html>`);
});

// ─── v2 Generate endpoint ─────────────────────────────────────────────────────

app.post('/generate-v2', upload.single('pdf'), async (req, res) => {
  try {
    const { q1, q2, q3, url } = req.body;
    const brief = [q1, q2, q3].filter(Boolean).map((s, i) => {
      const labels = ['Users and needs', 'Service goals', 'Content principles'];
      return labels[i] + ': ' + s.trim();
    }).join('\n\n');
    const apiKey = process.env.ANTHROPIC_API_KEY;
    const githubToken = process.env.GITHUB_TOKEN;
    const renderApiKey = process.env.RENDER_API_KEY;
    const renderOwnerId = process.env.RENDER_OWNER_ID;
    const githubUsername = process.env.GITHUB_USERNAME;

    if (!apiKey) return res.status(500).json({ error: 'ANTHROPIC_API_KEY not set' });
    if (!githubToken) return res.status(500).json({ error: 'GITHUB_TOKEN not set' });
    if (!renderApiKey) return res.status(500).json({ error: 'RENDER_API_KEY not set' });
    if (!renderOwnerId) return res.status(500).json({ error: 'RENDER_OWNER_ID not set' });
    if (!githubUsername) return res.status(500).json({ error: 'GITHUB_USERNAME not set' });
    if (!q1 || q1.trim().length < 5) return res.status(400).json({ error: 'Tell us who the users are and what they need' });

    // Step 1: PDF summarisation
    let pdfSummary = null;
    let pdfTruncated = false;
    if (req.file) {
      try {
        const pdfData = await pdfParse(req.file.buffer);
        let pdfText = pdfData.text;
        if (pdfText.length > 15000) {
          if (pdfText.length > 80000) {
            pdfText = pdfText.slice(0, 80000);
            pdfTruncated = true;
          }
          try {
            const summaryResponse = await fetch('https://api.anthropic.com/v1/messages', {
              method: 'POST',
              headers: {
                'Content-Type': 'application/json',
                'x-api-key': apiKey,
                'anthropic-version': '2023-06-01'
              },
              body: JSON.stringify({
                model: 'claude-sonnet-4-6',
                max_tokens: 2000,
                system: 'You are a government policy analyst. You will receive a service brief and a policy document. Extract and summarise only the content relevant to the brief. Return a clean markdown summary covering: eligibility rules and criteria, evidence requirements, key process steps and timeframes, any user-facing terminology that must be used, and any exclusions or special cases. Be concise. Maximum 1500 words.',
                messages: [{ role: 'user', content: `Brief: ${brief.trim()}\n\nDocument:\n${pdfText}` }]
              })
            });
            if (summaryResponse.ok) {
              const summaryData = await summaryResponse.json();
              pdfSummary = summaryData.content[0].text.trim();
            }
          } catch (e) {
            console.error('PDF summarisation failed, continuing without summary:', e.message);
          }
        } else {
          pdfSummary = pdfText;
        }
      } catch (e) {
        console.error('PDF parsing failed:', e.message);
      }
    }

    // Step 2: Claude generation
    let userMessage = `Brief: ${brief.trim()}`;
    if (pdfSummary) {
      userMessage += `\n\nPolicy document summary — use this to inform eligibility rules, question wording, hints, confirmation content, and any guidance:\n${pdfSummary}`;
    }
    if (url && url.trim()) userMessage += `\n\nReference URL: ${url.trim()}`;
    userMessage += '\n\nReturn only the JSON object. No explanation. No markdown.';

    const claudeResponse = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': apiKey,
        'anthropic-version': '2023-06-01'
      },
      body: JSON.stringify({
        model: 'claude-sonnet-4-6',
        max_tokens: 8000,
        system: gdsPromptV2,
        messages: [{ role: 'user', content: userMessage }]
      })
    });

    if (!claudeResponse.ok) {
      const err = await claudeResponse.json();
      throw new Error(err.error?.message || 'Claude API error');
    }

    const claudeData = await claudeResponse.json();
    const rawText = claudeData.content[0].text.trim();

    let spec;
    try {
      const clean = rawText.replace(/^```json\s*/i, '').replace(/^```\s*/i, '').replace(/```\s*$/i, '').trim();
      spec = JSON.parse(clean);
    } catch (e) {
      throw new Error('Claude returned invalid JSON. Try simplifying your brief.');
    }

    if (!spec.serviceName || !spec.questions || spec.questions.length < 1) {
      throw new Error('Prototype spec incomplete. Try again.');
    }

    // Step 3: Build and push to GitHub
    const files = buildPrototypeFilesV2(spec);
    const timestamp = Date.now();
    const repoName = `prototype-${timestamp}`;

    await createGitHubRepo(repoName, githubToken);
    await pushAllFiles(githubUsername, repoName, files, githubToken);

    const repoUrl = `https://github.com/${githubUsername}/${repoName}`;

    // Step 3: Create Render service
    const serviceName = `prototype-${timestamp}`;
    const renderData = await createRenderService(repoUrl, serviceName, renderApiKey, renderOwnerId);

    const serviceId = renderData.service?.id;
    if (!serviceId) throw new Error('Render did not return a service ID');

    // Step 4: Poll until actually live
    const protoUrl = `https://${serviceName}.onrender.com`;
    await pollUntilLive(protoUrl);
    await new Promise(r => setTimeout(r, 20000));

    // Log it (fire and forget)
    appendToLog({
      serviceName: spec.serviceName,
      brief: brief.trim().slice(0, 120),
      url: protoUrl,
      repoUrl,
      createdAt: new Date().toISOString()
    }, githubUsername, githubToken).catch(e => console.error('Log write failed:', e));

    res.json({ url: protoUrl, repoUrl, pdfTruncated });

  } catch (err) {
    console.error(err);
    if (!res.headersSent) res.status(500).json({ error: err.message });
  }
});

// ─── v3 Frontend ──────────────────────────────────────────────────────────────

app.get('/v3', (req, res) => {
  res.send(`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Build a prototype – Prototype Engine</title>
  <style>
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: "GDS Transport", arial, sans-serif; background: #f3f2f1; min-height: 100vh; display: flex; flex-direction: column; }
    main { max-width: 960px; margin: 0 auto; padding: 40px 30px; flex: 1; width: 100%; }

    h1 { font-size: 48px; font-weight: 700; color: #0b0c0c; line-height: 1.1; margin-bottom: 20px; }
    .lede { font-size: 20px; color: #0b0c0c; margin-bottom: 40px; line-height: 1.5; }
    label { display: block; font-size: 19px; font-weight: 700; color: #0b0c0c; margin-bottom: 8px; }
    .hint { font-size: 16px; color: #505a5f; margin-bottom: 10px; }
    textarea, input[type="text"], input[type="url"] { width: 100%; padding: 10px; font-size: 19px; font-family: inherit; border: 2px solid #0b0c0c; border-radius: 0; background: white; color: #0b0c0c; margin-bottom: 24px; }
    textarea:focus, input:focus { outline: 3px solid #ffdd00; outline-offset: 0; box-shadow: inset 0 0 0 2px #0b0c0c; }
    textarea { resize: vertical; }
    .file-upload-label { display: inline-block; padding: 8px 14px; background: #f3f2f1; border: 2px solid #0b0c0c; cursor: pointer; font-size: 16px; margin-bottom: 8px; }
    .file-name { font-size: 16px; color: #505a5f; margin-bottom: 24px; }
    input[type="file"] { display: none; }
    .generate-btn { background: #00703c; color: white; border: none; padding: 13px 22px; font-size: 19px; font-weight: 700; font-family: inherit; cursor: pointer; display: flex; align-items: center; gap: 10px; }
    .generate-btn:hover { background: #005a30; }
    .generate-btn:focus { outline: 3px solid #ffdd00; outline-offset: 0; }
    .generate-btn:disabled { background: #00703c; opacity: 0.75; cursor: wait; }
    .btn-arrow { width: 20px; height: 20px; fill: white; }

    /* Progress bar */
    .progress-panel { display: none; margin-top: 24px; background: white; border: 1px solid #d8dde0; border-radius: 6px; padding: 24px; }
    .progress-panel.visible { display: block; animation: fadeIn 0.2s ease; }
    .progress-bar-track { background: #f3f2f1; height: 4px; margin-bottom: 24px; border-radius: 2px; overflow: hidden; }
    .progress-bar-fill { height: 4px; background: #1d70b8; width: 0%; transition: width 0.6s ease; border-radius: 2px; }
    .progress-bar-fill.complete { background: #00703c; }
    .progress-steps { list-style: none; padding: 0; }
    .progress-steps li { font-size: 14px; color: #b1b4b6; padding: 9px 0; display: flex; align-items: center; gap: 12px; border-bottom: 1px solid #f3f2f1; transition: color 0.2s; }
    .progress-steps li:last-child { border-bottom: none; }
    .progress-steps li.active { color: #0b0c0c; font-weight: 600; }
    .progress-steps li.done { color: #00703c; }
    .step-icon { width: 16px; text-align: center; font-size: 12px; flex-shrink: 0; }

    /* Done panel */
    .done-panel { display: none; margin-top: 30px; background: white; border-left: 5px solid #00703c; padding: 24px; }
    .done-panel.visible { display: block; animation: fadeIn 0.4s ease; }
    @keyframes fadeIn { from { opacity: 0; transform: translateY(8px); } to { opacity: 1; transform: translateY(0); } }
    .done-header { display: flex; align-items: center; gap: 14px; margin-bottom: 16px; }
    .done-tick-circle { width: 40px; height: 40px; border-radius: 50%; background: #00703c; display: flex; align-items: center; justify-content: center; flex-shrink: 0; animation: popIn 0.4s cubic-bezier(0.34,1.56,0.64,1) both; }
    @keyframes popIn { from { transform: scale(0); } to { transform: scale(1); } }
    .done-tick-circle svg { width: 22px; height: 22px; fill: none; stroke: white; stroke-width: 3; stroke-linecap: round; stroke-linejoin: round; }
    .done-tick-circle svg path { stroke-dasharray: 40; stroke-dashoffset: 40; animation: drawTick 0.35s ease 0.3s forwards; }
    @keyframes drawTick { to { stroke-dashoffset: 0; } }
    .done-title { font-size: 24px; font-weight: 700; color: #0b0c0c; }
    .done-sub { font-size: 16px; color: #505a5f; margin-bottom: 20px; }
    .open-proto-btn { display: inline-block; background: #1d70b8; color: white; padding: 12px 20px; font-size: 19px; font-weight: 700; font-family: inherit; text-decoration: none; }
    .open-proto-btn:hover { background: #003078; }

    /* Error panel */
    .error-panel { display: none; margin-top: 30px; background: white; border-left: 5px solid #d4351c; padding: 24px; }
    .error-panel.visible { display: block; }
    .error-title { font-size: 19px; font-weight: 700; color: #0b0c0c; margin-bottom: 8px; }
    .error-msg { font-size: 16px; color: #505a5f; }

    /* Spinner */
    .spinner { display: inline-block; width: 16px; height: 16px; border: 2px solid rgba(255,255,255,0.4); border-top-color: white; border-radius: 50%; animation: spin 0.7s linear infinite; }
    @keyframes spin { to { transform: rotate(360deg); } }

    footer { background: #ffffff; padding: 20px 30px; color: #0b0c0c; border-top: 1px solid #b1b4b6; font-size: 14px; text-align: center; }
    @media (max-width: 768px) { h1 { font-size: 32px; } }
  </style>
</head>
<body>
<header style="background:#e0531a;padding:12px 0;border-bottom:none;">
  <div style="max-width:960px;margin:0 auto;padding:0 30px;">
    <a href="/" style="text-decoration:none;display:inline-flex;align-items:center;gap:10px;">
      <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
        <rect x="0" y="0" width="11" height="11" fill="white"/>
        <rect x="13" y="0" width="11" height="11" fill="white" fill-opacity="0.5"/>
        <rect x="0" y="13" width="11" height="11" fill="white" fill-opacity="0.5"/>
        <rect x="13" y="13" width="11" height="11" fill="white"/>
      </svg>
      <span style="color:white;font-size:15px;font-weight:700;font-family:arial,sans-serif;letter-spacing:-0.3px;">Prototype Engine</span>
    </a>
  </div>
</header>
<main>
<div style="max-width: 600px;">
    <div>
      <h1>Build a GOV.UK prototype</h1>
      <p class="lede">Describe your service and Claude will build a working GOV.UK prototype — no code required.</p>
      <form id="generateForm" enctype="multipart/form-data">
        <div>
          <label for="q1">Who are the users and what are their needs?</label>
          <textarea id="q1" name="q1" rows="3" placeholder="e.g. Parents applying for free school meals"></textarea>
        </div>
        <div>
          <label for="q2">What does the service need to achieve?</label>
          <textarea id="q2" name="q2" rows="3" placeholder="e.g. Help parents check eligibility and apply"></textarea>
        </div>
        <div>
          <label for="q3">What content principles should we apply?</label>
          <textarea id="q3" name="q3" rows="3" placeholder="e.g. Plain English, no jargon"></textarea>
        </div>
        <div>
          <label for="pdf">Upload a PDF (optional)</label>
          <p class="hint">Policy documents, existing service specs, research findings.</p>
          <label class="file-upload-label" for="pdf">Choose file</label>
          <input type="file" id="pdf" name="pdf" accept=".pdf">
          <div class="file-name" id="fileName">No file chosen</div>
        </div>
        <div>
          <label for="url">Reference URL (optional)</label>
          <p class="hint">A live service or document to reference.</p>
          <input type="url" id="url" name="url" placeholder="https://www.gov.uk/example">
        </div>
        <button type="submit" class="generate-btn" id="generateBtn">
          <span id="btnText">Generate prototype</span>
          <svg class="btn-arrow" id="btnArrow" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 60 60">
            <path d="M0 20h40l-8-8 4-4 16 16-16 16-4-4 8-8H0z"/>
          </svg>
        </button>
      </form>

      <!-- Progress panel -->
      <div class="progress-panel" id="progressPanel">
        <div class="progress-bar-track">
          <div class="progress-bar-fill" id="progressBar"></div>
        </div>
        <ul class="progress-steps">
          <li id="step-pdf" style="display:none;"><span class="step-icon" id="icon-pdf">–</span> Reading document</li>
          <li id="step-claude"><span class="step-icon" id="icon-claude">–</span> Generating with Claude</li>
          <li id="step-github"><span class="step-icon" id="icon-github">–</span> Pushing to GitHub</li>
          <li id="step-render"><span class="step-icon" id="icon-render">–</span> Creating Render service</li>
          <li id="step-deploy"><span class="step-icon" id="icon-deploy">–</span> Waiting for prototype to go live</li>
        </ul>
      </div>

      <!-- Done panel -->
      <div class="done-panel" id="donePanel">
        <div class="done-header">
          <div class="done-tick-circle">
            <svg viewBox="0 0 24 24"><path d="M4 12l5 5L20 7"/></svg>
          </div>
          <div class="done-title">Your prototype is live</div>
        </div>
        <p class="done-sub">It is ready to use. Share the link with your team.</p>
        <a href="#" id="openProtoBtn" class="open-proto-btn" target="_blank" rel="noopener">Open prototype</a>
        <div id="pdfTruncatedNotice" style="display:none; margin-top: 20px; padding: 15px 20px; border-left: 10px solid #b1b4b6; font-size: 16px; color: #0b0c0c;">Your document was long so we summarised the most relevant parts. The prototype is based on that summary.</div>
      </div>

      <!-- Error panel -->
      <div class="error-panel" id="errorPanel">
        <div class="error-title">Something went wrong</div>
        <div class="error-msg" id="errorMsg"></div>
      </div>
    </div>

  </div>
</main>
<footer>Built on GOV.UK Prototype Kit v13 &middot; Powered by Claude</footer>

<script>
  document.getElementById('pdf').addEventListener('change', function() {
    document.getElementById('fileName').textContent = this.files[0] ? this.files[0].name : 'No file chosen';
  });

  function setStep(stepId, iconId, state) {
    const li = document.getElementById(stepId);
    const icon = document.getElementById(iconId);
    li.className = state;
    if (state === 'active') icon.textContent = '●';
    else if (state === 'done') icon.textContent = '✓';
    else icon.textContent = '–';
  }

  let progressTimer = null;

  function startFakeProgress(hasPdf) {
    const bar = document.getElementById('progressBar');
    const pdfStep = document.getElementById('step-pdf');
    let steps;

    if (hasPdf) {
      pdfStep.style.display = '';
      steps = [
        { stepId: 'step-pdf',     iconId: 'icon-pdf',     delay: 0,     pct: 10 },
        { stepId: 'step-claude',  iconId: 'icon-claude',  delay: 12000, pct: 25 },
        { stepId: 'step-github',  iconId: 'icon-github',  delay: 24000, pct: 50 },
        { stepId: 'step-render',  iconId: 'icon-render',  delay: 36000, pct: 65 },
        { stepId: 'step-deploy',  iconId: 'icon-deploy',  delay: 50000, pct: 80 }
      ];
    } else {
      pdfStep.style.display = 'none';
      steps = [
        { stepId: 'step-claude',  iconId: 'icon-claude',  delay: 0,     pct: 15 },
        { stepId: 'step-github',  iconId: 'icon-github',  delay: 18000, pct: 45 },
        { stepId: 'step-render',  iconId: 'icon-render',  delay: 30000, pct: 65 },
        { stepId: 'step-deploy',  iconId: 'icon-deploy',  delay: 45000, pct: 80 }
      ];
    }

    let prevStepId = null, prevIconId = null;
    steps.forEach(function(s) {
      const t = setTimeout(function() {
        if (prevStepId) setStep(prevStepId, prevIconId, 'done');
        setStep(s.stepId, s.iconId, 'active');
        bar.style.width = s.pct + '%';
        prevStepId = s.stepId;
        prevIconId = s.iconId;
      }, s.delay);
      if (!progressTimer) progressTimer = [];
      progressTimer.push(t);
    });
  }

  function stopFakeProgress() {
    if (progressTimer) progressTimer.forEach(clearTimeout);
    progressTimer = null;
  }

  document.getElementById('generateForm').addEventListener('submit', async function(e) {
    e.preventDefault();

    const btn = document.getElementById('generateBtn');
    const btnText = document.getElementById('btnText');
    const btnArrow = document.getElementById('btnArrow');
    const progressPanel = document.getElementById('progressPanel');
    const donePanel = document.getElementById('donePanel');
    const errorPanel = document.getElementById('errorPanel');
    const bar = document.getElementById('progressBar');
    const hasPdf = document.getElementById('pdf').files.length > 0;

    donePanel.className = 'done-panel';
    errorPanel.className = 'error-panel';
    document.getElementById('pdfTruncatedNotice').style.display = 'none';
    progressPanel.className = 'progress-panel visible';
    bar.style.width = '5%';
    bar.className = 'progress-bar-fill';
    var allSteps = ['step-claude','step-github','step-render','step-deploy'];
    if (hasPdf) allSteps.unshift('step-pdf');
    allSteps.forEach(function(id) {
      document.getElementById(id).className = '';
      var iconId = 'icon-' + id.replace('step-', '');
      document.getElementById(iconId).textContent = '–';
    });

    btn.disabled = true;
    btnArrow.style.display = 'none';
    btnText.innerHTML = '<span class="spinner"></span> Generating&hellip;';

    startFakeProgress(hasPdf);

    try {
      const formData = new FormData(this);
      const response = await fetch('/generate-v3', { method: 'POST', body: formData });

      stopFakeProgress();

      if (!response.ok) {
        const err = await response.json().catch(function() { return { error: 'Unknown error' }; });
        throw new Error(err.error || 'Something went wrong');
      }

      const result = await response.json();

      bar.style.width = '100%';
      bar.className = 'progress-bar-fill complete';
      var doneSteps = ['step-claude','step-github','step-render','step-deploy'];
      if (hasPdf) doneSteps.unshift('step-pdf');
      doneSteps.forEach(function(id) {
        setStep(id, 'icon-' + id.replace('step-', ''), 'done');
      });

      progressPanel.className = 'progress-panel';
      document.getElementById('openProtoBtn').href = result.url;
      donePanel.className = 'done-panel visible';

      if (result.pdfTruncated) {
        document.getElementById('pdfTruncatedNotice').style.display = 'block';
      }

    } catch (err) {
      stopFakeProgress();
      progressPanel.className = 'progress-panel';
      document.getElementById('errorMsg').textContent = err.message || 'Try again or simplify your brief.';
      errorPanel.className = 'error-panel visible';
    }

    btn.disabled = false;
    btnArrow.style.display = '';
    btnText.textContent = 'Generate prototype';
  });
</script>
</body>
</html>`);
});

// ─── v3 Generate endpoint (uses v2 branching logic) ──────────────────────────

app.post('/generate-v3', upload.single('pdf'), async (req, res) => {
  try {
    const { q1, q2, q3, url } = req.body;
    const brief = [q1, q2, q3].filter(Boolean).map((s, i) => {
      const labels = ['Users and needs', 'Service goals', 'Content principles'];
      return labels[i] + ': ' + s.trim();
    }).join('\n\n');
    const apiKey = process.env.ANTHROPIC_API_KEY;
    const githubToken = process.env.GITHUB_TOKEN;
    const renderApiKey = process.env.RENDER_API_KEY;
    const renderOwnerId = process.env.RENDER_OWNER_ID;
    const githubUsername = process.env.GITHUB_USERNAME;

    if (!apiKey) return res.status(500).json({ error: 'ANTHROPIC_API_KEY not set' });
    if (!githubToken) return res.status(500).json({ error: 'GITHUB_TOKEN not set' });
    if (!renderApiKey) return res.status(500).json({ error: 'RENDER_API_KEY not set' });
    if (!renderOwnerId) return res.status(500).json({ error: 'RENDER_OWNER_ID not set' });
    if (!githubUsername) return res.status(500).json({ error: 'GITHUB_USERNAME not set' });
    if (!q1 || q1.trim().length < 5) return res.status(400).json({ error: 'Tell us who the users are and what they need' });

    // Step 1: PDF summarisation
    let pdfSummary = null;
    let pdfTruncated = false;
    if (req.file) {
      try {
        const pdfData = await pdfParse(req.file.buffer);
        let pdfText = pdfData.text;
        if (pdfText.length > 15000) {
          if (pdfText.length > 80000) {
            pdfText = pdfText.slice(0, 80000);
            pdfTruncated = true;
          }
          try {
            const summaryResponse = await fetch('https://api.anthropic.com/v1/messages', {
              method: 'POST',
              headers: {
                'Content-Type': 'application/json',
                'x-api-key': apiKey,
                'anthropic-version': '2023-06-01'
              },
              body: JSON.stringify({
                model: 'claude-sonnet-4-6',
                max_tokens: 2000,
                system: 'You are a government policy analyst. You will receive a service brief and a policy document. Extract and summarise only the content relevant to the brief. Return a clean markdown summary covering: eligibility rules and criteria, evidence requirements, key process steps and timeframes, any user-facing terminology that must be used, and any exclusions or special cases. Be concise. Maximum 1500 words.',
                messages: [{ role: 'user', content: `Brief: ${brief.trim()}\n\nDocument:\n${pdfText}` }]
              })
            });
            if (summaryResponse.ok) {
              const summaryData = await summaryResponse.json();
              pdfSummary = summaryData.content[0].text.trim();
            }
          } catch (e) {
            console.error('PDF summarisation failed, continuing without summary:', e.message);
          }
        } else {
          pdfSummary = pdfText;
        }
      } catch (e) {
        console.error('PDF parsing failed:', e.message);
      }
    }

    // Step 2: Claude generation (using v2 branching prompt and builder)
    let userMessage = `Brief: ${brief.trim()}`;
    if (pdfSummary) {
      userMessage += `\n\nPolicy document summary — use this to inform eligibility rules, question wording, hints, confirmation content, and any guidance:\n${pdfSummary}`;
    }
    if (url && url.trim()) userMessage += `\n\nReference URL: ${url.trim()}`;
    userMessage += '\n\nReturn only the JSON object. No explanation. No markdown.';

    const claudeResponse = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': apiKey,
        'anthropic-version': '2023-06-01'
      },
      body: JSON.stringify({
        model: 'claude-sonnet-4-6',
        max_tokens: 8000,
        system: gdsPromptV2,
        messages: [{ role: 'user', content: userMessage }]
      })
    });

    if (!claudeResponse.ok) {
      const err = await claudeResponse.json();
      throw new Error(err.error?.message || 'Claude API error');
    }

    const claudeData = await claudeResponse.json();
    const rawText = claudeData.content[0].text.trim();

    let spec;
    try {
      const clean = rawText.replace(/^```json\s*/i, '').replace(/^```\s*/i, '').replace(/```\s*$/i, '').trim();
      spec = JSON.parse(clean);
    } catch (e) {
      throw new Error('Claude returned invalid JSON. Try simplifying your brief.');
    }

    if (!spec.serviceName || !spec.questions || spec.questions.length < 1) {
      throw new Error('Prototype spec incomplete. Try again.');
    }

    // Step 3: Build and push to GitHub
    const files = buildPrototypeFilesV2(spec);
    const timestamp = Date.now();
    const repoName = `prototype-${timestamp}`;

    await createGitHubRepo(repoName, githubToken);
    await pushAllFiles(githubUsername, repoName, files, githubToken);

    const repoUrl = `https://github.com/${githubUsername}/${repoName}`;

    // Step 4: Create Render service
    const serviceName = `prototype-${timestamp}`;
    const renderData = await createRenderService(repoUrl, serviceName, renderApiKey, renderOwnerId);

    const serviceId = renderData.service?.id;
    if (!serviceId) throw new Error('Render did not return a service ID');

    // Step 5: Poll until actually live
    const protoUrl = `https://${serviceName}.onrender.com`;
    await pollUntilLive(protoUrl);
    await new Promise(r => setTimeout(r, 20000));

    // Log it (fire and forget)
    appendToLog({
      serviceName: spec.serviceName,
      brief: brief.trim().slice(0, 120),
      url: protoUrl,
      repoUrl,
      createdAt: new Date().toISOString()
    }, githubUsername, githubToken).catch(e => console.error('Log write failed:', e));

    res.json({ url: protoUrl, repoUrl, pdfTruncated });

  } catch (err) {
    console.error(err);
    if (!res.headersSent) res.status(500).json({ error: err.message });
  }
});

// ─── Prototypes log page ──────────────────────────────────────────────────────

app.get('/prototypes', async (req, res) => {
  const githubToken = process.env.GITHUB_TOKEN;
  const githubUsername = process.env.GITHUB_USERNAME;
  const fullLog = await getLog(githubUsername, githubToken);

  // Split into new (after cutoff, page 1) and old (before cutoff, page 2+)
  const newProtos = fullLog.filter(e => e.createdAt >= V3_DEMO_CUTOFF);
  const oldProtos = fullLog.filter(e => e.createdAt < V3_DEMO_CUTOFF);

  const page = Math.max(1, parseInt(req.query.page, 10) || 1);
  const pageSize = 10;
  let log, pageLog, totalPages, currentPage;

  if (page === 1) {
    log = fullLog;
    pageLog = newProtos;
    totalPages = Math.max(1, 1 + Math.ceil(oldProtos.length / pageSize));
    currentPage = 1;
  } else {
    log = fullLog;
    const oldPage = page - 1; // page 2 = first page of old protos
    totalPages = Math.max(1, 1 + Math.ceil(oldProtos.length / pageSize));
    currentPage = Math.min(page, totalPages);
    const start = (oldPage - 1) * pageSize;
    pageLog = oldProtos.slice(start, start + pageSize);
  }

  function timeAgo(iso) {
    const diff = Date.now() - new Date(iso).getTime();
    const mins = Math.floor(diff / 60000);
    const hours = Math.floor(diff / 3600000);
    const days = Math.floor(diff / 86400000);
    if (mins < 2) return 'just now';
    if (mins < 60) return mins + ' minutes ago';
    if (hours < 24) return hours + ' hour' + (hours > 1 ? 's' : '') + ' ago';
    return days + ' day' + (days > 1 ? 's' : '') + ' ago';
  }

  res.send(`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>All prototypes — Transform Prototype Engine</title>
  <style>
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: "GDS Transport", arial, sans-serif; background: #f3f2f1; min-height: 100vh; display: flex; flex-direction: column; }
    main { max-width: 960px; margin: 0 auto; padding: 48px 30px 80px; flex: 1; width: 100%; }
    .page-header { display: flex; align-items: center; justify-content: space-between; margin-bottom: 32px; flex-wrap: wrap; gap: 16px; }
    .page-header-left h1 { font-size: 32px; font-weight: 700; color: #0b0c0c; letter-spacing: -0.5px; }
    .page-header-left p { font-size: 14px; color: #6f777b; margin-top: 4px; font-weight: 500; }
    .new-btn { background: #00703c; color: white; text-decoration: none; padding: 10px 18px; font-size: 16px; font-weight: 700; font-family: inherit; white-space: nowrap; }
    .new-btn:hover { background: #005a30; }
    .proto-list { display: flex; flex-direction: column; gap: 1px; background: #d8dde0; border: 1px solid #d8dde0; overflow: hidden; }
    .proto-card { background: white; padding: 20px 24px; display: flex; align-items: center; justify-content: space-between; gap: 24px; transition: background 0.1s; }
    .proto-card:hover { background: #f8f8f8; }
    .proto-card-left { flex: 1; min-width: 0; }
    .proto-name { font-size: 19px; font-weight: 700; color: #0b0c0c; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
    .proto-meta { font-size: 16px; color: #505a5f; margin-top: 3px; }
    .proto-card-right { flex-shrink: 0; width: 160px; display: flex; justify-content: flex-end; }
    .open-link { display: inline-flex; align-items: center; justify-content: center; width: 160px; background: #1d70b8; color: white; text-decoration: none; padding: 10px 0; font-size: 16px; font-weight: 700; font-family: inherit; }
    .open-link:hover { background: #003078; }
    .empty-state { background: white; border: 1px solid #b1b4b6; padding: 60px 30px; text-align: center; color: #505a5f; font-size: 16px; }
    footer { background: #ffffff; padding: 20px 30px; color: #0b0c0c; border-top: 1px solid #b1b4b6; font-size: 14px; text-align: center; }
  </style>
</head>
<body>
<header style="background:#e0531a;padding:12px 0;border-bottom:none;">
  <div style="max-width:960px;margin:0 auto;padding:0 30px;">
    <a href="/" style="text-decoration:none;display:inline-flex;align-items:center;gap:10px;">
      <svg class="pe-logo" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
        <rect x="0" y="0" width="11" height="11" fill="white"/>
        <rect x="13" y="0" width="11" height="11" fill="white" fill-opacity="0.5"/>
        <rect x="0" y="13" width="11" height="11" fill="white" fill-opacity="0.5"/>
        <rect x="13" y="13" width="11" height="11" fill="white"/>
      </svg>
      <span style="color:white;font-size:15px;font-weight:700;font-family:arial,sans-serif;letter-spacing:-0.3px;">Prototype Engine</span>
    </a>
  </div>
</header>
<main>
  <div class="page-header">
    <div class="page-header-left">
      <h1>All prototypes</h1>
      <p>${log.length} generated</p>
    </div>
  </div>
  ${log.length === 0
    ? '<div class="empty-state">No prototypes generated yet.</div>'
    : '<div class="proto-list">' + pageLog.map(function(entry) {
        return '<div class="proto-card">' +
          '<div class="proto-card-left">' +
            '<div class="proto-name">' + entry.serviceName + '</div>' +
            '<div class="proto-meta">' + timeAgo(entry.createdAt) + '</div>' +
          '</div>' +
          '<div class="proto-card-right">' +
            '<a href="' + entry.url + '" target="_blank" rel="noopener" class="open-link">Open prototype</a>' +
          '</div>' +
        '</div>';
      }).join('') + '</div>'
  }
  ${totalPages > 1 ? '<nav style="display:flex;align-items:center;justify-content:space-between;margin-top:24px;font-size:16px;font-family:\'GDS Transport\',arial,sans-serif;">' +
    (currentPage > 1 ? '<a href="/prototypes?page=' + (currentPage - 1) + '" style="color:#1d70b8;font-weight:700;text-decoration:none;">&larr; Newer</a>' : '<span></span>') +
    '<span style="color:#505a5f;">Page ' + currentPage + ' of ' + totalPages + '</span>' +
    (currentPage < totalPages ? '<a href="/prototypes?page=' + (currentPage + 1) + '" style="color:#1d70b8;font-weight:700;text-decoration:none;">Older &rarr;</a>' : '<span></span>') +
    '</nav>' : ''}
  <p style="margin-top:24px;font-size:15px;"><a href="/" style="color:#505a5f;">← Back</a></p>
</main>
<footer>GOV.UK Prototype Kit v13 &middot; Powered by Claude Sonnet</footer>
</body>
</html>`);
});

// ─── Design history ──────────────────────────────────────────────────────────

function renderDesignHistoryEntry(entry) {
  var whatChangedHtml = '';
  if (entry.whatChanged && entry.whatChanged.length > 0) {
    whatChangedHtml = '<ul style="font-size:19px;line-height:1.6;padding-left:20px;margin-top:10px;">' +
      entry.whatChanged.map(function(item) { return '<li>' + item + '</li>'; }).join('') +
      '</ul>';
  } else {
    whatChangedHtml = '<p style="font-size:19px;line-height:1.6;color:#505a5f;">None yet.</p>';
  }
  return '<div style="margin-bottom:50px;padding-bottom:50px;border-bottom:1px solid #b1b4b6;">' +
    '<h2 style="font-size:36px;font-weight:700;color:#0b0c0c;margin-bottom:5px;">' + entry.title + '</h2>' +
    '<p style="font-size:16px;color:#505a5f;margin-bottom:30px;">Last updated: ' + entry.date + '</p>' +
    '<h3 style="font-size:24px;font-weight:700;color:#0b0c0c;margin-bottom:10px;">Problem</h3>' +
    '<p style="font-size:19px;line-height:1.6;margin-bottom:30px;">' + entry.problem + '</p>' +
    '<h3 style="font-size:24px;font-weight:700;color:#0b0c0c;margin-bottom:10px;">Our approach</h3>' +
    '<p style="font-size:19px;line-height:1.6;margin-bottom:30px;">' + entry.approach + '</p>' +
    '<h3 style="font-size:24px;font-weight:700;color:#0b0c0c;margin-bottom:10px;">What changed</h3>' +
    '<div style="margin-bottom:30px;">' + whatChangedHtml + '</div>' +
    '<h3 style="font-size:24px;font-weight:700;color:#0b0c0c;margin-bottom:10px;">Next steps</h3>' +
    '<p style="font-size:19px;line-height:1.6;">' + entry.nextSteps + '</p>' +
  '</div>';
}

app.get('/design-history', (req, res) => {
  var v1 = JSON.parse(fs.readFileSync(path.join(__dirname, 'app', 'design-history', 'v1.json'), 'utf8'));
  var v2 = JSON.parse(fs.readFileSync(path.join(__dirname, 'app', 'design-history', 'v2.json'), 'utf8'));
  var v3 = JSON.parse(fs.readFileSync(path.join(__dirname, 'app', 'design-history', 'v3.json'), 'utf8'));
  var versions = [v1, v2, v3];

  res.send(`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Design history – Prototype Engine</title>
  <style>
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: "GDS Transport", arial, sans-serif; background: #f3f2f1; min-height: 100vh; display: flex; flex-direction: column; }
    main { max-width: 960px; margin: 0 auto; padding: 40px 30px; flex: 1; width: 100%; }
    h1 { font-size: 48px; font-weight: 700; color: #0b0c0c; line-height: 1.1; margin-bottom: 10px; }
    .lede { font-size: 20px; color: #0b0c0c; margin-bottom: 40px; line-height: 1.5; }
    .version-list { list-style: none; padding: 0; display: flex; flex-direction: column; gap: 1px; background: #d8dde0; border: 1px solid #d8dde0; }
    .version-card { background: white; padding: 24px; display: flex; align-items: center; justify-content: space-between; gap: 20px; }
    .version-card:hover { background: #f8f8f8; }
    .version-info { flex: 1; }
    .version-name { font-size: 24px; font-weight: 700; color: #1d70b8; text-decoration: none; }
    .version-name:hover { text-decoration: underline; }
    .version-date { font-size: 16px; color: #505a5f; margin-top: 4px; }
    footer { background: #ffffff; padding: 20px 30px; color: #0b0c0c; border-top: 1px solid #b1b4b6; font-size: 14px; text-align: center; }
    @media (max-width: 768px) { h1 { font-size: 32px; } }
  </style>
</head>
<body>
<header style="background:#e0531a;padding:12px 0;border-bottom:none;">
  <div style="max-width:960px;margin:0 auto;padding:0 30px;">
    <a href="/" style="text-decoration:none;display:inline-flex;align-items:center;gap:10px;">
      <svg class="pe-logo" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
        <rect x="0" y="0" width="11" height="11" fill="white"/>
        <rect x="13" y="0" width="11" height="11" fill="white" fill-opacity="0.5"/>
        <rect x="0" y="13" width="11" height="11" fill="white" fill-opacity="0.5"/>
        <rect x="13" y="13" width="11" height="11" fill="white"/>
      </svg>
      <span style="color:white;font-size:15px;font-weight:700;font-family:arial,sans-serif;letter-spacing:-0.3px;">Prototype Engine</span>
    </a>
  </div>
</header>
<main>
  <h1>Design history</h1>
  <p class="lede">A record of what we built, why we built it, and what changed in each version.</p>
  <ul class="version-list">
` + versions.map(function(v) {
    var latestDate = v.entries[0] ? v.entries[0].date : '';
    return '    <li class="version-card"><div class="version-info"><a href="/design-history/' + v.version + '" class="version-name">' + v.version + ': ' + v.title + '</a><p class="version-date">' + latestDate + '</p></div></li>';
  }).join('\n') + `
  </ul>
</main>
<footer>Built on GOV.UK Prototype Kit v13 &middot; Powered by Claude</footer>
</body>
</html>`);
});

app.get('/design-history/:version', (req, res) => {
  var version = req.params.version;
  var filePath = path.join(__dirname, 'app', 'design-history', version + '.json');
  if (!fs.existsSync(filePath)) {
    return res.status(404).send('Not found');
  }
  var data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
  var entriesHtml = data.entries.map(renderDesignHistoryEntry).join('');

  res.send(`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${data.version}: ${data.title} – Design history – Prototype Engine</title>
  <style>
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: "GDS Transport", arial, sans-serif; background: #f3f2f1; min-height: 100vh; display: flex; flex-direction: column; }
    main { max-width: 960px; margin: 0 auto; padding: 40px 30px; flex: 1; width: 100%; }
    footer { background: #ffffff; padding: 20px 30px; color: #0b0c0c; border-top: 1px solid #b1b4b6; font-size: 14px; text-align: center; }
    @media (max-width: 768px) { h1 { font-size: 32px; } }
  </style>
</head>
<body>
<header style="background:#e0531a;padding:12px 0;border-bottom:none;">
  <div style="max-width:960px;margin:0 auto;padding:0 30px;">
    <a href="/" style="text-decoration:none;display:inline-flex;align-items:center;gap:10px;">
      <svg class="pe-logo" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
        <rect x="0" y="0" width="11" height="11" fill="white"/>
        <rect x="13" y="0" width="11" height="11" fill="white" fill-opacity="0.5"/>
        <rect x="0" y="13" width="11" height="11" fill="white" fill-opacity="0.5"/>
        <rect x="13" y="13" width="11" height="11" fill="white"/>
      </svg>
      <span style="color:white;font-size:15px;font-weight:700;font-family:arial,sans-serif;letter-spacing:-0.3px;">Prototype Engine</span>
    </a>
  </div>
</header>
<main>
  <p style="font-size:16px;margin-bottom:20px;"><a href="/design-history" style="color:#1d70b8;">&larr; Back to design history</a></p>
  <h1 style="font-size:48px;font-weight:700;color:#0b0c0c;line-height:1.1;margin-bottom:40px;">${data.version}: ${data.title}</h1>
  ${entriesHtml}
</main>
<footer>Built on GOV.UK Prototype Kit v13 &middot; Powered by Claude</footer>
</body>
</html>`);
});

app.get('/roadmap', (req, res) => {
  res.send(`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>How the tool works – Prototype Engine</title>
  <style>
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: "GDS Transport", arial, sans-serif; background: #f3f2f1; min-height: 100vh; display: flex; flex-direction: column; }
    main { max-width: 960px; margin: 0 auto; padding: 40px 30px; flex: 1; width: 100%; }
    .govuk-width-container { max-width: 640px; }
    .govuk-heading-l { font-size: 48px; font-weight: 700; color: #0b0c0c; line-height: 1.1; margin-bottom: 30px; }
    .govuk-heading-m { font-size: 27px; font-weight: 700; color: #0b0c0c; margin-top: 40px; margin-bottom: 15px; }
    .govuk-body { font-size: 19px; color: #0b0c0c; line-height: 1.6; margin-bottom: 20px; }
    .govuk-list { font-size: 19px; color: #0b0c0c; line-height: 1.6; margin-bottom: 20px; padding-left: 0; list-style: none; }
    .govuk-list--bullet { padding-left: 20px; list-style-type: disc; }
    .govuk-list--bullet li { margin-bottom: 5px; }
    footer { background: #ffffff; padding: 20px 30px; color: #0b0c0c; border-top: 1px solid #b1b4b6; font-size: 14px; text-align: center; }
    @media (max-width: 768px) { .govuk-heading-l { font-size: 32px; } .govuk-heading-m { font-size: 22px; } }
  </style>
</head>
<body>
<header style="background:#e0531a;padding:12px 0;border-bottom:none;">
  <div style="max-width:960px;margin:0 auto;padding:0 30px;">
    <a href="/" style="text-decoration:none;display:inline-flex;align-items:center;gap:10px;">
      <svg class="pe-logo" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
        <rect x="0" y="0" width="11" height="11" fill="white"/>
        <rect x="13" y="0" width="11" height="11" fill="white" fill-opacity="0.5"/>
        <rect x="0" y="13" width="11" height="11" fill="white" fill-opacity="0.5"/>
        <rect x="13" y="13" width="11" height="11" fill="white"/>
      </svg>
      <span style="color:white;font-size:15px;font-weight:700;font-family:arial,sans-serif;letter-spacing:-0.3px;">Prototype Engine</span>
    </a>
  </div>
</header>
<main>
  <div class="govuk-width-container">
    <h1 class="govuk-heading-l">How the tool works</h1>

    <h2 class="govuk-heading-m">What it does</h2>
    <p class="govuk-body">This tool is a research and development project exploring how AI can help content designers prototype GOV.UK services faster. It generates a working prototype from a plain English brief in around 5 minutes — no code required.</p>

    <h2 class="govuk-heading-m">Who it is for</h2>
    <p class="govuk-body">It is designed for content designers. It can also be used by product managers, policy professionals, and user researchers.</p>

    <h2 class="govuk-heading-m">Why it works this way</h2>
    <p class="govuk-body">The tool wraps Claude in a controlled environment. This makes output consistent, predictable, and shareable across the team. Each release is tested for stability before new capabilities are added. If something goes wrong, we can roll back without affecting what already works.</p>

    <h2 class="govuk-heading-m">What it does well</h2>
    <p class="govuk-body">Every prototype includes:</p>
    <ul class="govuk-list govuk-list--bullet">
      <li>A start page, question pages, check your answers, and a confirmation screen</li>
      <li>Validation on every question</li>
      <li>Automatic deployment to a shareable URL</li>
    </ul>
    <p class="govuk-body">Version 2 adds branching journeys, where different answers lead to different pages.</p>

    <h2 class="govuk-heading-m">Current limitations</h2>
    <p class="govuk-body">The tool is at an early stage. The biggest limitation right now is content and design quality.</p>
    <p class="govuk-body">Specifically:</p>
    <ul class="govuk-list govuk-list--bullet">
      <li>Generated content is functional but lacks the design thinking a content designer would apply manually</li>
      <li>Question wording, hint text, and confirmation pages often need significant revision</li>
      <li>Journeys cover the main flow but not edge cases, exception routes, or nuanced policy decisions</li>
      <li>The full range of GDS patterns is not yet supported</li>
    </ul>
    <p class="govuk-body">Improving content and design quality is the primary focus of v3.</p>

    <h2 class="govuk-heading-m">Known unknowns</h2>
    <p class="govuk-body">As an R&D project, there are things we are still working out:</p>
    <ul class="govuk-list govuk-list--bullet">
      <li>How much complexity the tool can support before the workflow breaks down</li>
      <li>How it performs with multiple concurrent users</li>
      <li>How much work a future GOV.UK Prototype Kit update would require</li>
    </ul>

    <h2 class="govuk-heading-m">Next steps</h2>
    <p class="govuk-body">Each version introduces one new capability, tested for stability before the next begins.</p>

    <div style="max-width:560px;margin:24px 0;font-family:'GDS Transport',arial,sans-serif;">
      <div style="padding:14px 20px;margin-bottom:4px;background:#0b5c3e;width:100%;display:flex;align-items:center;justify-content:space-between;">
        <span style="font-size:15px;font-weight:700;color:white;">v1 — Foundation</span>
        <span style="font-size:11px;font-weight:700;padding:2px 8px;text-transform:uppercase;letter-spacing:0.05em;background:#00703c;color:white;">Stable</span>
      </div>
      <div style="padding:14px 20px;margin-bottom:4px;background:#1d70b8;width:80%;display:flex;align-items:center;justify-content:space-between;">
        <span style="font-size:15px;font-weight:700;color:white;">v2 — Branching</span>
        <span style="font-size:11px;font-weight:700;padding:2px 8px;text-transform:uppercase;letter-spacing:0.05em;background:#003078;color:white;">In testing</span>
      </div>
      <div style="padding:14px 20px;margin-bottom:4px;background:#505a5f;width:60%;display:flex;align-items:center;justify-content:space-between;">
        <span style="font-size:15px;font-weight:700;color:white;">v3 — Content and patterns</span>
        <span style="font-size:11px;font-weight:700;padding:2px 8px;text-transform:uppercase;letter-spacing:0.05em;background:#383f43;color:white;">Planned</span>
      </div>
      <div style="padding:14px 20px;margin-bottom:4px;background:#b1b4b6;width:55%;display:flex;align-items:center;justify-content:space-between;">
        <span style="font-size:15px;font-weight:700;color:#0b0c0c;">v4 — Edit mode</span>
        <span style="font-size:11px;font-weight:700;padding:2px 8px;text-transform:uppercase;letter-spacing:0.05em;background:#6f777b;color:white;">Planned</span>
      </div>
      <p style="font-size:13px;color:#505a5f;margin-top:16px;">Each layer is confirmed stable before the next begins.</p>
    </div>
  </div>
</main>
<footer>Built on GOV.UK Prototype Kit v13 &middot; Powered by Claude</footer>
</body>
</html>`);
});

const port = process.env.PORT || 3000;
app.listen(port, () => console.log(`Prototype Engine running on port ${port}`));
